### PR TITLE
Update GNOME runtime to version 47 

### PR DESCRIPTION
**Pull request by yakushabb**
- GNOME runtime version 45 has reached EOL.
- Fix appdata papercuts

### CODE REVIEW

**Comment by ghost** [comment]
@Eonfge ready for review.

**Comment by Eonfge** [comment]
bot, build

**Comment by Eonfge** [comment]
I was on holiday but I will take a look at it now

**Comment by Eonfge** [comment]
Looks good to me. @barthalion Can you merge this, since I don't have maintainer status on this package?

**Pull request merged**
