### PR TITLE
Update runtime to GNOME 43

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by KevinAtSesam** [comment]
@leonardschardijn Tested it at the office and it works fine

**Comment by leonardschardijn** [comment]
Hey, are you sure it works fine?

Because in my system both GNOME 42 and GNOME 43 make the file contents go under the navigation buttons or the description panel.

It seems that the font sizes provided by Pango that the application uses to calculate how many bytes to print were changed in the versions that are included in GNOME 42 and GNOME 43.

To be able to work with these new versions of Pango the bytes-per-line calculations done by the application need to be changed. I'm quite busy for the moment, but I can try to take a look at it at some point.

**Comment by Eonfge** [comment]
bot, build

**Comment by Eonfge** [comment]
I haven't seen anything different in the UI

Screenshot from 2022-10-10 11-56-15

[Screencast from 10-10-22 11:54:26.webm](https://user-images.githubusercontent.com/33983090/194840993-535b0c18-2048-4763-ba6b-95fd314a8063.webm)

**Comment by leonardschardijn** [comment]
The thing is that when you let the application calculate how many bytes to print, it is supposed to print just enough bytes to fill out the file contents area, like this (GNOME 41):

GNOME 41

But when I change to GNOME 43 this happens:

GNOME 43

I'm still not sure about what is causing this different behavior, I thought it may be the Pango-provided font sizes that the application uses, but I'm not even completely sure about that. I'd like to fix this issue before updating to GNOME 43, but I don't have much time currently.

**Pull request closed without merging**
